apiVersion: v1
kind: ConfigMap
metadata:
  name: ttcs-config
data:
  APP_ENV: production
  DB_HOST: ttcs-postgresql
  DB_PORT: "5432"
  DB_DATABASE: ttcs
  DB_USERNAME: ttcs
  RABBITMQ_HOST: ttcs-rabbitmq
  RABBITMQ_PORT: "5672"
  REDIS_HOST: ttcs-redis
  REDIS_PORT: "6379"
  APP_URL: https://api.ttcs.dev
  CORS_ALLOWED_ORIGINS: "https://ttcs.dev"
  LOG_CHANNEL: stack
  BROADCAST_DRIVER: redis
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: rabbitmq
  SESSION_DRIVER: redis